/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkOrdersIndexRouteImport } from './routes/_app.work-orders.index'
import { Route as AppVehiclesIndexRouteImport } from './routes/_app.vehicles.index'
import { Route as AppTechIndexRouteImport } from './routes/_app.tech.index'
import { Route as AppServiceAdvisorIndexRouteImport } from './routes/_app.service-advisor.index'
import { Route as AppPortalIndexRouteImport } from './routes/_app.portal.index'
import { Route as AppOwnerIndexRouteImport } from './routes/_app.owner.index'
import { Route as AppMessagesIndexRouteImport } from './routes/_app.messages.index'
import { Route as AppManagerIndexRouteImport } from './routes/_app.manager.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppWorkOrdersIdRouteImport } from './routes/_app.work-orders.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkOrdersIndexRoute = AppWorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AppRoute,
} as any)
const AppTechIndexRoute = AppTechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceAdvisorIndexRoute = AppServiceAdvisorIndexRouteImport.update({
  id: '/service-advisor/',
  path: '/service-advisor/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalIndexRoute = AppPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerIndexRoute = AppOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerIndexRoute = AppManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkOrdersIdRoute = AppWorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/work-orders/$id': typeof AppWorkOrdersIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/manager/': typeof AppManagerIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/owner/': typeof AppOwnerIndexRoute
  '/portal/': typeof AppPortalIndexRoute
  '/service-advisor/': typeof AppServiceAdvisorIndexRoute
  '/tech/': typeof AppTechIndexRoute
  '/vehicles/': typeof AppVehiclesIndexRoute
  '/work-orders/': typeof AppWorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/work-orders/$id': typeof AppWorkOrdersIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/manager': typeof AppManagerIndexRoute
  '/messages': typeof AppMessagesIndexRoute
  '/owner': typeof AppOwnerIndexRoute
  '/portal': typeof AppPortalIndexRoute
  '/service-advisor': typeof AppServiceAdvisorIndexRoute
  '/tech': typeof AppTechIndexRoute
  '/vehicles': typeof AppVehiclesIndexRoute
  '/work-orders': typeof AppWorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/work-orders/$id': typeof AppWorkOrdersIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/manager/': typeof AppManagerIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/_app/owner/': typeof AppOwnerIndexRoute
  '/_app/portal/': typeof AppPortalIndexRoute
  '/_app/service-advisor/': typeof AppServiceAdvisorIndexRoute
  '/_app/tech/': typeof AppTechIndexRoute
  '/_app/vehicles/': typeof AppVehiclesIndexRoute
  '/_app/work-orders/': typeof AppWorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/admin/users'
    | '/work-orders/$id'
    | '/customers/'
    | '/inventory/'
    | '/invoices/'
    | '/manager/'
    | '/messages/'
    | '/owner/'
    | '/portal/'
    | '/service-advisor/'
    | '/tech/'
    | '/vehicles/'
    | '/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/admin/users'
    | '/work-orders/$id'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/manager'
    | '/messages'
    | '/owner'
    | '/portal'
    | '/service-advisor'
    | '/tech'
    | '/vehicles'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pending'
    | '/signup'
    | '/_app/admin/users'
    | '/_app/work-orders/$id'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/invoices/'
    | '/_app/manager/'
    | '/_app/messages/'
    | '/_app/owner/'
    | '/_app/portal/'
    | '/_app/service-advisor/'
    | '/_app/tech/'
    | '/_app/vehicles/'
    | '/_app/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/work-orders/': {
      id: '/_app/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AppWorkOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles/': {
      id: '/_app/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tech/': {
      id: '/_app/tech/'
      path: '/tech'
      fullPath: '/tech/'
      preLoaderRoute: typeof AppTechIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service-advisor/': {
      id: '/_app/service-advisor/'
      path: '/service-advisor'
      fullPath: '/service-advisor/'
      preLoaderRoute: typeof AppServiceAdvisorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/': {
      id: '/_app/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AppPortalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/': {
      id: '/_app/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AppOwnerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/': {
      id: '/_app/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AppManagerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-orders/$id': {
      id: '/_app/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof AppWorkOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppWorkOrdersIdRoute: typeof AppWorkOrdersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppManagerIndexRoute: typeof AppManagerIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppOwnerIndexRoute: typeof AppOwnerIndexRoute
  AppPortalIndexRoute: typeof AppPortalIndexRoute
  AppServiceAdvisorIndexRoute: typeof AppServiceAdvisorIndexRoute
  AppTechIndexRoute: typeof AppTechIndexRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
  AppWorkOrdersIndexRoute: typeof AppWorkOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppWorkOrdersIdRoute: AppWorkOrdersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppManagerIndexRoute: AppManagerIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppOwnerIndexRoute: AppOwnerIndexRoute,
  AppPortalIndexRoute: AppPortalIndexRoute,
  AppServiceAdvisorIndexRoute: AppServiceAdvisorIndexRoute,
  AppTechIndexRoute: AppTechIndexRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
  AppWorkOrdersIndexRoute: AppWorkOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
